# -- Site Configuration --

# URL to the root of your website.
baseURL = "https://wildanhaq.github.io"

# Site's language code
languageCode = 'en-us'

title = "Wildan's Workspace"

theme = "kayal" # UNCOMMENT THIS LINE

# Number of articles per page in the listing.
paginate = 30

# Enable processing of emojis in markdown.
enableEmoji = true

# Enable creation of robots.txt for search engine crawling.
enableRobotsTXT = true

# Length of default summaries.
summaryLength = 20

# Build drafts during site generation.
buildDrafts = false

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

# Google Analytics Configuration
# [services]
#   [services.googleAnalytics]
#     ID = 'G-MEASUREMENT_ID'
